
version: '2.1'
networks:
  test:
    name: fabric_test

services:

##### couchdb01 #####
  couchdb01:
    extends:
      file: common-all.yaml
      service: common-couch
    container_name: couchdb01
    ports:
      - "7984:5984"
    networks:
      - test

  peer0.org1.example.com:
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb01:5984
    depends_on:
      - couchdb01
    networks:
      - test

##### couchdb02 #####
  couchdb02:
    extends:
      file: common-all.yaml
      service: common-couch
    container_name: couchdb02
    ports:
      - "8984:5984"
    networks:
      - test

  peer0.org2.example.com:
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb02:5984
    depends_on:
      - couchdb02
    networks:
      - test

##### couchdb03 #####
  couchdb03:
    extends:
      file: common-all.yaml
      service: common-couch
    container_name: couchdb03
    ports:
      - "9984:5984"
    networks:
      - test

  peer0.org3.example.com:
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb03:5984
    depends_on:
      - couchdb03
    networks:
      - test

##### couchdb04 #####
  couchdb04:
    extends:
      file: common-all.yaml
      service: common-couch
    container_name: couchdb04
    ports:
      - "10984:5984"
    networks:
      - test

  peer0.org4.example.com:
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb04:5984
    depends_on:
      - couchdb04
    networks:
      - test

