# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2.1'

networks:
  test:
    name: fabric_test

services:
  couchdb10:
    container_name: couchdb10
    extends:
      file: common-all.yaml
      service: common-couch
    ports:
      - "5984:5984"

  couchdb11:
    container_name: couchdb11
    extends:
      file: common-all.yaml
      service: common-couch
    ports:
      - "5985:5984"

  couchdb12:
    container_name: couchdb12
    extends:
      file: common-all.yaml
      service: common-couch
    ports:
      - "5986:5984"

  couchdb13:
    container_name: couchdb13
    extends:
      file: common-all.yaml
      service: common-couch
    ports:
      - "5987:5984"

  couchdb20:
    container_name: couchdb20
    extends:
      file: common-all.yaml
      service: common-couch
    ports:
      - "6984:5984"
  
  couchdb21:  
    container_name: couchdb21
    extends:
      file: common-all.yaml
      service: common-couch
    ports:
      - "6985:5984"

  couchdb22:
    container_name: couchdb22
    extends:
      file: common-all.yaml
      service: common-couch
    ports:
      - "6986:5984"

  couchdb23:
    container_name: couchdb23
    extends:
      file: common-all.yaml
      service: common-couch
    ports:
      - "6987:5984"
  
  couchdb30:
    container_name: couchdb30
    extends:
      file: common-all.yaml
      service: common-couch
    ports:
      - "7984:5984"

  couchdb31:
    container_name: couchdb31
    extends:
      file: common-all.yaml
      service: common-couch
    ports:
      - "7985:5984"

  couchdb32:
    container_name: couchdb32
    extends:
      file: common-all.yaml
      service: common-couch
    ports:
      - "7986:5984"

  couchdb33:
    container_name: couchdb33
    extends:
      file: common-all.yaml
      service: common-couch
    ports:
      - "7987:5984"

  couchdb40:
    container_name: couchdb40
    extends:
      file: common-all.yaml
      service: common-couch
    ports:
      - "8984:5984"

  couchdb41:
    container_name: couchdb41
    extends:
      file: common-all.yaml
      service: common-couch
    ports:
      - "8985:5984"

  couchdb42:
    container_name: couchdb42
    extends:
      file: common-all.yaml
      service: common-couch
    ports:
      - "8986:5984"

  couchdb43:
    container_name: couchdb43
    extends:
      file: common-all.yaml
      service: common-couch
    ports:
      - "8987:5984"


  peer0.org1.example.com:
    extends:
      file: common-all.yaml
      service: common-peer
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb105984
    depends_on:
      - couchdb10

  peer1.org1.example.com:
    extends:
      file: common-all.yaml
      service: common-peer
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb11:5984
    depends_on:
      - couchdb11

  peer2.org1.example.com:
    extends:
      file: common-all.yaml
      service: common-peer
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb12:5984
    depends_on:
      - couchdb12

  peer3.org1.example.com:
    extends:
      file: common-all.yaml
      service: common-peer
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb13:5984
    depends_on:
      - couchdb13

  peer0.org2.example.com:
    extends:
      file: common-all.yaml
      service: common-peer
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb20:5984
    depends_on:
      - couchdb20

  peer1.org2.example.com:
    extends:
      file: common-all.yaml
      service: common-peer
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb21:5984
    depends_on:
      - couchdb21

  peer2.org2.example.com:
    extends:
      file: common-all.yaml
      service: common-peer
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb22:5984
    depends_on:
      - couchdb22

  peer3.org2.example.com:
    extends:
      file: common-all.yaml
      service: common-peer
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb23:5984
    depends_on:
      - couchdb23

  peer0.org3.example.com:
    extends:
      file: common-all.yaml
      service: common-peer
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb30:5984
    depends_on:
      - couchdb30

  peer1.org3.example.com:
    extends:
      file: common-all.yaml
      service: common-peer
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb31:5984
    depends_on:
      - couchdb31

  peer2.org3.example.com:
    extends:
      file: common-all.yaml
      service: common-peer
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb32:5984
    depends_on:
      - couchdb32

  peer3.org3.example.com:
    extends:
      file: common-all.yaml
      service: common-peer
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb33:5984
    depends_on:
      - couchdb33

  peer0.org4.example.com:
    extends:
      file: common-all.yaml
      service: common-peer
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb40:5984
    depends_on:
      - couchdb40
  
  peer1.org4.example.com:
    extends:
      file: common-all.yaml
      service: common-peer
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb41:5984
    depends_on:
      - couchdb41

  peer2.org4.example.com:
    extends:
      file: common-all.yaml
      service: common-peer
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb42:5984
    depends_on:
      - couchdb42

  peer3.org4.example.com:
    extends:
      file: common-all.yaml
      service: common-peer
    environment:
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb43:5984
    depends_on:
      - couchdb43
  